/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Salome Tambe
 */
public class student_dept extends javax.swing.JFrame {

    /**
     * Creates new form student_dept
     */
    public student_dept() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        registered = new javax.swing.JButton();
        students_class = new javax.swing.JButton();
        stud_female = new javax.swing.JButton();
        stud_male = new javax.swing.JButton();
        students_dept = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registered = new javax.swing.JTable();
        remove = new javax.swing.JButton();
        dept = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.darkGray));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        registered.setBackground(new java.awt.Color(0, 0, 0));
        registered.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registered.setForeground(new java.awt.Color(255, 255, 255));
        registered.setText("Registered");
        registered.setBorderPainted(false);
        registered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredActionPerformed(evt);
            }
        });

        students_class.setBackground(new java.awt.Color(0, 0, 0));
        students_class.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        students_class.setForeground(new java.awt.Color(255, 255, 255));
        students_class.setText("Students per Class");
        students_class.setBorderPainted(false);
        students_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_classActionPerformed(evt);
            }
        });

        stud_female.setBackground(new java.awt.Color(0, 0, 0));
        stud_female.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stud_female.setForeground(new java.awt.Color(255, 255, 255));
        stud_female.setText("Female Students");
        stud_female.setBorderPainted(false);
        stud_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_femaleActionPerformed(evt);
            }
        });

        stud_male.setBackground(new java.awt.Color(0, 0, 0));
        stud_male.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stud_male.setForeground(new java.awt.Color(255, 255, 255));
        stud_male.setText("Male Students");
        stud_male.setBorderPainted(false);
        stud_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_maleActionPerformed(evt);
            }
        });

        students_dept.setBackground(new java.awt.Color(0, 0, 0));
        students_dept.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        students_dept.setForeground(new java.awt.Color(255, 255, 255));
        students_dept.setText("Students per Department");
        students_dept.setBorderPainted(false);
        students_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_deptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(students_class)
                    .addComponent(stud_female)
                    .addComponent(stud_male)
                    .addComponent(registered)
                    .addComponent(students_dept))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(registered, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(students_class)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(students_dept)
                .addGap(12, 12, 12)
                .addComponent(stud_female)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud_male)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Students per Department");

        Registered.setBackground(new java.awt.Color(255, 255, 255));
        Registered.setForeground(new java.awt.Color(0, 0, 0));
        Registered.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Firstname", "Surname", "Sex", "Education", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Registered.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(Registered);

        remove.setBackground(new java.awt.Color(0, 0, 0));
        remove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove Student(s)");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        dept.setBackground(new java.awt.Color(0, 0, 0));
        dept.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dept.setForeground(new java.awt.Color(255, 255, 255));
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Rural Engineering", "Town Planning", "Land Surveying" }));

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remove)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(search)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registeredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredActionPerformed
        // TODO add your handling code here:
        try {
            students menu = new students();
            menu.setVisible(true);
            setVisible(false);

        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_registeredActionPerformed

    private void students_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_classActionPerformed
        // TODO add your handling code here:
        try {
            student_class menu = new student_class();
            menu.setVisible(true);
            setVisible(false);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_students_classActionPerformed

    private void stud_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_femaleActionPerformed
        // TODO add your handling code here:
        try {
            stud_female menu = new stud_female();
            menu.setVisible(true);
            setVisible(false);

        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_stud_femaleActionPerformed

    private void stud_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_maleActionPerformed
        // TODO add your handling code here:
        try {
            stud_male menu = new stud_male();
            menu.setVisible(true);
            setVisible(false);

        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_stud_maleActionPerformed

    private void students_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_students_deptActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_dept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Registered;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registered;
    private javax.swing.JButton remove;
    private javax.swing.JButton search;
    private javax.swing.JButton stud_female;
    private javax.swing.JButton stud_male;
    private javax.swing.JButton students_class;
    private javax.swing.JButton students_dept;
    // End of variables declaration//GEN-END:variables
}
